### ISSUE TITLE
Default login

### ISSUE THREAD

**Issue by kubeworkz** [Chemchu/ERPWeb#46]
Is there a default uid and password? Great project btw. Cheers, Dave

**Comment by Chemchu** [comment]
Hi Dave! Thanks for the comment.
The website on this repository's details is not a demo and people can't really interact with it, at least not right now. Sorry about the confusion. I am still working on this project.
If you want to deploy this solution by yourself, the default username and password is:

Username:  admin@erp.com
Password: admin

I recommend you to delete this user once you've added your own account. 
If you have any comments or any questions, feel free to ask me anytime!
